[package]
name = "lexi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "run_tg_bot"
path = "src/bin/run_tg_bot.rs"

[[bin]]
name = "chat_cli"
path = "src/bin/chat_cli.rs"

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.41", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.31"
indoc = "2.0.6"
mockall = "0.13.1"
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "migrate",
    "chrono",
    "json",
    "bigdecimal",
] }
tokio = { version = "1.46.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "fmt",
    "json",
] }

[dev-dependencies]
mockito = "1.7.0"
tempfile = "3.20.0"
