[package]
name = "lexi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "run_tg_bot"
path = "src/bin/run_tg_bot.rs"

[[bin]]
name = "chat_cli"
path = "src/bin/chat_cli.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6"
dotenv = "0.15"
eyre = "0.6"
futures = "0.3"
indoc = "2.0"
mockall = "0.13"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "migrate",
    "chrono",
    "json",
    "bigdecimal",
] }
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
] }

[dev-dependencies]
mockito = "1.7"
tempfile = "3.20"
