services:
  test_db:
    image: postgres:16
    container_name: lexi_test_postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # Expose on host port 5433 to avoid conflict with default 5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
    driver: local 