on: push

env:
  CARGO_TERM_COLOR: always

name: check-lint-test

jobs:
  check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check

  # check-schema:
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v4

  #     - run: rustup toolchain install stable --profile minimal

  #     # check if this speeds anything up
  #     - uses: Swatinem/rust-cache@v2

  #     - name: Install sqlx-cli
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: install
  #         args: sqlx-cli

  #     - name: Run sqlx check
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: sqlx
  #         args: prepare --check -- --all-targets

  lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings

  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test -- --nocapture
